import {
  Restaurant,
  Branch,
  Category,
  Product,
  Order,
  DeliveryBoy,
  Staff,
  Coupon,
  Offer,
  User,
  NotificationItem,
} from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "u-1",
    name: "Vikram Malhotra",
    email: "admin@foodkingdom.com",
    role: "SUPER_ADMIN",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
    phone: "+91 98765 43210",
  },
  {
    id: "u-2",
    name: "Rajesh Sharma",
    email: "owner@foodkingdom.com",
    role: "OWNER",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    restaurantId: "rest-1",
    phone: "+91 98112 33445",
  },
  {
    id: "u-3",
    name: "Amit Verma",
    email: "kanpur.mgr@foodkingdom.com",
    role: "BRANCH_MANAGER",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
    restaurantId: "rest-1",
    branchId: "branch-kanpur",
    phone: "+91 94551 12233",
  },
  {
    id: "u-4",
    name: "Chef Suresh Kumar",
    email: "kitchen@foodkingdom.com",
    role: "KITCHEN_STAFF",
    avatar: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=150&q=80",
    restaurantId: "rest-1",
    branchId: "branch-kanpur",
    phone: "+91 97998 87766",
  },
  {
    id: "u-5",
    name: "Rohan Singh",
    email: "rohan.delivery@foodkingdom.com",
    role: "DELIVERY_BOY",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80",
    restaurantId: "rest-1",
    branchId: "branch-kanpur",
    phone: "+91 96543 21098",
  },
];

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: "rest-1",
    name: "Food Kingdom",
    slug: "food-kingdom",
    logo: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    ownerName: "Rajesh Sharma",
    ownerEmail: "owner@foodkingdom.com",
    phone: "+91 98112 33445",
    status: "ACTIVE",
    totalBranches: 3,
    totalRevenue: 2450000,
    rating: 4.8,
    createdAt: "2024-01-15",
  },
  {
    id: "rest-2",
    name: "Spice Route Express",
    slug: "spice-route",
    logo: "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80",
    ownerName: "Priya Kapoor",
    ownerEmail: "priya@spiceroute.com",
    phone: "+91 98990 11223",
    status: "ACTIVE",
    totalBranches: 2,
    totalRevenue: 1280000,
    rating: 4.6,
    createdAt: "2024-03-01",
  },
  {
    id: "rest-3",
    name: "Urban Bistro & Grill",
    slug: "urban-bistro",
    logo: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=300&q=80",
    banner: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80",
    ownerName: "Kabir Mehta",
    ownerEmail: "kabir@urbanbistro.com",
    phone: "+91 97112 88990",
    status: "ACTIVE",
    totalBranches: 4,
    totalRevenue: 3100000,
    rating: 4.9,
    createdAt: "2023-11-10",
  },
];

export const MOCK_BRANCHES: Branch[] = [
  {
    id: "branch-kanpur",
    restaurantId: "rest-1",
    name: "Food Kingdom - Kanpur",
    city: "Kanpur",
    address: "112, Swaroop Nagar, Opposite Moti Jheel, Kanpur - 208002",
    managerName: "Amit Verma",
    phone: "+91 94551 12233",
    status: "OPEN",
    kitchenStatus: "OPERATIONAL",
    openingTime: "10:00 AM",
    closingTime: "11:30 PM",
    deliveryRadiusKm: 8,
    todayOrdersCount: 48,
    todayRevenue: 42500,
  },
  {
    id: "branch-lucknow",
    restaurantId: "rest-1",
    name: "Food Kingdom - Lucknow",
    city: "Lucknow",
    address: "45, Hazratganj Main Road, Lucknow - 226001",
    managerName: "Ritu Singhania",
    phone: "+91 94551 44556",
    status: "OPEN",
    kitchenStatus: "HIGH_LOAD",
    openingTime: "10:00 AM",
    closingTime: "11:59 PM",
    deliveryRadiusKm: 10,
    todayOrdersCount: 65,
    todayRevenue: 68900,
  },
  {
    id: "branch-delhi",
    restaurantId: "rest-1",
    name: "Food Kingdom - Delhi",
    city: "Delhi",
    address: "Sector 18, Near Atta Market, Noida/Delhi NCR - 201301",
    managerName: "Deepak Joshi",
    phone: "+91 98119 00112",
    status: "OPEN",
    kitchenStatus: "OPERATIONAL",
    openingTime: "09:00 AM",
    closingTime: "01:00 AM",
    deliveryRadiusKm: 12,
    todayOrdersCount: 82,
    todayRevenue: 94200,
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Burgers & Sandwiches",
    slug: "burgers-sandwiches",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80",
    itemCount: 8,
    status: "ACTIVE",
  },
  {
    id: "cat-2",
    name: "Pizzas & Pastas",
    slug: "pizzas-pastas",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=400&q=80",
    itemCount: 12,
    status: "ACTIVE",
  },
  {
    id: "cat-3",
    name: "Biryani & Bowls",
    slug: "biryani-bowls",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=400&q=80",
    itemCount: 10,
    status: "ACTIVE",
  },
  {
    id: "cat-4",
    name: "Starters & Appetizers",
    slug: "starters-appetizers",
    image: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=400&q=80",
    itemCount: 14,
    status: "ACTIVE",
  },
  {
    id: "cat-5",
    name: "Desserts & Shakes",
    slug: "desserts-shakes",
    image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=400&q=80",
    itemCount: 9,
    status: "ACTIVE",
  },
  {
    id: "cat-6",
    name: "Beverages & Cold Drinks",
    slug: "beverages",
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=400&q=80",
    itemCount: 6,
    status: "ACTIVE",
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    restaurantId: "rest-1",
    branchIds: ["branch-kanpur", "branch-lucknow", "branch-delhi"],
    name: "Royal Supreme Cheese Burger",
    description: "Double grilled crispy patty with caramelized onions, sharp cheddar cheese, and signature secret sauce.",
    category: "Burgers & Sandwiches",
    price: 349,
    offerPrice: 299,
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80",
    isAvailable: true,
    stock: 45,
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 15,
  },
  {
    id: "prod-2",
    restaurantId: "rest-1",
    branchIds: ["branch-kanpur", "branch-lucknow", "branch-delhi"],
    name: "Truffle Mushroom Artisan Pizza",
    description: "Hand-tossed sourdough pizza topped with wild mushrooms, white truffle oil, and fresh mozzarella.",
    category: "Pizzas & Pastas",
    price: 599,
    offerPrice: 529,
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=400&q=80",
    isAvailable: true,
    stock: 30,
    isVeg: true,
    rating: 4.8,
    prepTimeMinutes: 20,
  },
  {
    id: "prod-3",
    restaurantId: "rest-1",
    branchIds: ["branch-kanpur", "branch-lucknow", "branch-delhi"],
    name: "Hyderabadi Dum Chicken Biryani",
    description: "Authentic long-grain basmati rice cooked on slow dum with tender marinated chicken and aromatics.",
    category: "Biryani & Bowls",
    price: 449,
    offerPrice: 399,
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=400&q=80",
    isAvailable: true,
    stock: 50,
    isVeg: false,
    rating: 4.9,
    prepTimeMinutes: 25,
  },
  {
    id: "prod-4",
    restaurantId: "rest-1",
    branchIds: ["branch-kanpur", "branch-lucknow"],
    name: "Paneer Tikka Charcoal Roll",
    description: "Clay oven roasted cottage cheese cubes wrapped in flaky paratha with mint chutney and pickled onions.",
    category: "Starters & Appetizers",
    price: 249,
    offerPrice: 219,
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=400&q=80",
    isAvailable: true,
    stock: 25,
    isVeg: true,
    rating: 4.7,
    prepTimeMinutes: 12,
  },
  {
    id: "prod-5",
    restaurantId: "rest-1",
    branchIds: ["branch-kanpur", "branch-lucknow", "branch-delhi"],
    name: "Belgian Chocolate Lava Cake",
    description: "Warm gooey chocolate cake with a molten center, served with vanilla bean gelato.",
    category: "Desserts & Shakes",
    price: 229,
    offerPrice: 199,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=400&q=80",
    isAvailable: true,
    stock: 18,
    isVeg: true,
    rating: 4.9,
    prepTimeMinutes: 10,
  },
  {
    id: "prod-6",
    restaurantId: "rest-1",
    branchIds: ["branch-kanpur", "branch-delhi"],
    name: "Fresh Mango Mint Cooler",
    description: "Chilled fresh Alphonso mango pulp blended with mint, lemon zest, and sparkling soda water.",
    category: "Beverages & Cold Drinks",
    price: 159,
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=400&q=80",
    isAvailable: true,
    stock: 60,
    isVeg: true,
    rating: 4.6,
    prepTimeMinutes: 5,
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-101",
    orderNumber: "FK-8891",
    restaurantId: "rest-1",
    branchId: "branch-kanpur",
    branchName: "Kanpur",
    customerName: "Aarav Sharma",
    customerPhone: "+91 98765 11223",
    customerAddress: "Flat 402, Royal Heights, Swaroop Nagar, Kanpur",
    items: [
      {
        productId: "prod-1",
        productName: "Royal Supreme Cheese Burger",
        quantity: 2,
        price: 299,
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=200&q=80",
        customizations: ["Extra Cheese", "No Onions"],
      },
      {
        productId: "prod-6",
        productName: "Fresh Mango Mint Cooler",
        quantity: 2,
        price: 159,
        image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=200&q=80",
      },
    ],
    subtotal: 916,
    tax: 45,
    deliveryFee: 40,
    totalAmount: 1001,
    paymentStatus: "PAID",
    paymentMethod: "UPI",
    orderType: "DELIVERY",
    status: "PREPARING",
    deliveryBoyId: "del-1",
    deliveryBoyName: "Rohan Singh",
    otp: "4829",
    createdAt: "2026-07-22T21:45:00Z",
    estimatedPrepTimeMinutes: 18,
    startedPrepAt: "2026-07-22T21:48:00Z",
  },
  {
    id: "ord-102",
    orderNumber: "FK-8892",
    restaurantId: "rest-1",
    branchId: "branch-kanpur",
    branchName: "Kanpur",
    customerName: "Sneha Patel",
    customerPhone: "+91 99188 77665",
    customerAddress: "House 14B, Civil Lines, Kanpur",
    items: [
      {
        productId: "prod-3",
        productName: "Hyderabadi Dum Chicken Biryani",
        quantity: 1,
        price: 399,
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=200&q=80",
      },
      {
        productId: "prod-5",
        productName: "Belgian Chocolate Lava Cake",
        quantity: 1,
        price: 199,
        image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=200&q=80",
      },
    ],
    subtotal: 598,
    tax: 30,
    deliveryFee: 30,
    totalAmount: 658,
    paymentStatus: "PAID",
    paymentMethod: "CREDIT_CARD",
    orderType: "DELIVERY",
    status: "READY",
    deliveryBoyId: "del-1",
    deliveryBoyName: "Rohan Singh",
    otp: "7103",
    createdAt: "2026-07-22T21:30:00Z",
    estimatedPrepTimeMinutes: 20,
    startedPrepAt: "2026-07-22T21:32:00Z",
  },
  {
    id: "ord-103",
    orderNumber: "FK-8893",
    restaurantId: "rest-1",
    branchId: "branch-lucknow",
    branchName: "Lucknow",
    customerName: "Mohit Verma",
    customerPhone: "+91 91234 56789",
    items: [
      {
        productId: "prod-2",
        productName: "Truffle Mushroom Artisan Pizza",
        quantity: 2,
        price: 529,
        image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=200&q=80",
      },
    ],
    subtotal: 1058,
    tax: 53,
    deliveryFee: 0,
    totalAmount: 1111,
    paymentStatus: "PAID",
    paymentMethod: "UPI",
    orderType: "TAKEAWAY",
    status: "OUT_FOR_DELIVERY",
    deliveryBoyId: "del-2",
    deliveryBoyName: "Karan Gupta",
    otp: "9512",
    createdAt: "2026-07-22T21:20:00Z",
    estimatedPrepTimeMinutes: 15,
  },
  {
    id: "ord-104",
    orderNumber: "FK-8894",
    restaurantId: "rest-1",
    branchId: "branch-delhi",
    branchName: "Delhi",
    customerName: "Ananya Roy",
    customerPhone: "+91 98111 22334",
    customerAddress: "Tower C, Sector 62, Noida, Delhi NCR",
    items: [
      {
        productId: "prod-1",
        productName: "Royal Supreme Cheese Burger",
        quantity: 3,
        price: 299,
        image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=200&q=80",
      },
    ],
    subtotal: 897,
    tax: 44,
    deliveryFee: 50,
    totalAmount: 991,
    paymentStatus: "PAID",
    paymentMethod: "UPI",
    orderType: "DELIVERY",
    status: "DELIVERED",
    deliveryBoyId: "del-3",
    deliveryBoyName: "Vikky Yadav",
    otp: "3391",
    createdAt: "2026-07-22T20:50:00Z",
    estimatedPrepTimeMinutes: 15,
  },
  {
    id: "ord-105",
    orderNumber: "FK-8895",
    restaurantId: "rest-1",
    branchId: "branch-kanpur",
    branchName: "Kanpur",
    customerName: "Rohan Trivedi",
    customerPhone: "+91 94150 99887",
    items: [
      {
        productId: "prod-4",
        productName: "Paneer Tikka Charcoal Roll",
        quantity: 2,
        price: 219,
        image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=200&q=80",
      },
    ],
    subtotal: 438,
    tax: 22,
    deliveryFee: 0,
    totalAmount: 460,
    paymentStatus: "PENDING",
    paymentMethod: "CASH_ON_DELIVERY",
    orderType: "DINE_IN",
    status: "PENDING",
    createdAt: "2026-07-22T22:05:00Z",
    estimatedPrepTimeMinutes: 12,
  },
];

export const MOCK_DELIVERY_BOYS: DeliveryBoy[] = [
  {
    id: "del-1",
    branchId: "branch-kanpur",
    branchName: "Kanpur",
    name: "Rohan Singh",
    phone: "+91 96543 21098",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80",
    status: "ON_DELIVERY",
    rating: 4.9,
    totalDeliveries: 342,
    activeOrderId: "ord-101",
    currentLocation: "Swaroop Nagar, 1.2 km away",
  },
  {
    id: "del-2",
    branchId: "branch-lucknow",
    branchName: "Lucknow",
    name: "Karan Gupta",
    phone: "+91 97888 11223",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80",
    status: "ON_DELIVERY",
    rating: 4.7,
    totalDeliveries: 289,
    activeOrderId: "ord-103",
    currentLocation: "Hazratganj Main Market",
  },
  {
    id: "del-3",
    branchId: "branch-delhi",
    branchName: "Delhi",
    name: "Vikky Yadav",
    phone: "+91 99112 44556",
    avatar: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=150&q=80",
    status: "AVAILABLE",
    rating: 4.85,
    totalDeliveries: 512,
    currentLocation: "Sector 18 Hub",
  },
];

export const MOCK_STAFF: Staff[] = [
  {
    id: "st-1",
    name: "Amit Verma",
    email: "amit.v@foodkingdom.com",
    phone: "+91 94551 12233",
    role: "BRANCH_MANAGER",
    branchId: "branch-kanpur",
    branchName: "Kanpur",
    status: "ACTIVE",
    joinedDate: "2023-05-10",
  },
  {
    id: "st-2",
    name: "Chef Suresh Kumar",
    email: "chef.suresh@foodkingdom.com",
    phone: "+91 97998 87766",
    role: "KITCHEN_STAFF",
    branchId: "branch-kanpur",
    branchName: "Kanpur",
    status: "ACTIVE",
    joinedDate: "2023-08-01",
  },
  {
    id: "st-3",
    name: "Ritu Singhania",
    email: "ritu.s@foodkingdom.com",
    phone: "+91 94551 44556",
    role: "BRANCH_MANAGER",
    branchId: "branch-lucknow",
    branchName: "Lucknow",
    status: "ACTIVE",
    joinedDate: "2023-06-15",
  },
];

export const MOCK_COUPONS: Coupon[] = [
  {
    id: "coup-1",
    code: "WELCOME50",
    title: "50% Off On First Order",
    discountType: "PERCENTAGE",
    discountValue: 50,
    minOrderValue: 299,
    validTill: "2026-12-31",
    status: "ACTIVE",
    branchScope: "ALL",
    usageCount: 1420,
  },
  {
    id: "coup-2",
    code: "KANPUR100",
    title: "Flat ₹100 Off Kanpur Special",
    discountType: "FLAT",
    discountValue: 100,
    minOrderValue: 499,
    validTill: "2026-08-31",
    status: "ACTIVE",
    branchScope: "branch-kanpur",
    usageCount: 310,
  },
  {
    id: "coup-3",
    code: "FREEDEL",
    title: "Zero Delivery Fee",
    discountType: "FLAT",
    discountValue: 40,
    minOrderValue: 199,
    validTill: "2026-09-15",
    status: "ACTIVE",
    branchScope: "ALL",
    usageCount: 890,
  },
];

export const MOCK_OFFERS: Offer[] = [
  {
    id: "off-1",
    title: "Monsoon Feast Festival",
    description: "Get up to 40% discount on all Gourmet Pizzas and Biryani Combos across branches.",
    banner: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80",
    type: "FESTIVAL",
    discountPercentage: 40,
    branchId: "ALL",
    status: "ACTIVE",
  },
  {
    id: "off-2",
    title: "Late Night Craving Hour",
    description: "Complimentary Chocolate Lava Cake on orders above ₹699 placed after 9 PM.",
    banner: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80",
    type: "COMBO",
    branchId: "branch-delhi",
    status: "ACTIVE",
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "notif-1",
    title: "New High Value Order",
    message: "Order #FK-8895 placed by Rohan Trivedi (₹460) - Kanpur Branch",
    time: "2 mins ago",
    read: false,
    type: "ORDER",
  },
  {
    id: "notif-2",
    title: "Kitchen Alert - Kanpur",
    message: "Kanpur kitchen has 3 preparing orders close to estimated target time.",
    time: "8 mins ago",
    read: false,
    type: "KITCHEN",
  },
  {
    id: "notif-3",
    title: "Delivery OTP Verified",
    message: "Rohan Singh verified OTP for Order #FK-8891.",
    time: "15 mins ago",
    read: true,
    type: "DELIVERY",
  },
];
